"""Configuration constants for raw product-card field extraction."""

RAW_PRODUCT_FIELD_KEYS = (
    "brand",
    "supplier",
    "producer",
    "manufacturer",
    "vendor",
    "country",
    "country_of_origin",
    "origin_country",
    "composition",
    "description",
    "weight",
    "volume",
    "unit",
    "packaging",
    "fat",
    "fat_percent",
    "sugar",
    "sugar_class",
    "color",
    "variant",
    "package_size",
    "protein",
    "carbohydrate",
    "calories",
    "shelf_life",
    "storage_conditions",
)

RAW_PRODUCT_FIELD_ALIASES = {
    "brand": ("brand_name", "brandName", "trademark"),
    "supplier": ("supplier_name", "supplierName"),
    "producer": ("producer_name", "producerName"),
    "manufacturer": ("manufacturer_name", "manufacturerName", "maker", "made_by"),
    "country": ("countryOfOrigin", "originCountry", "country_name"),
    "composition": ("ingredients", "ingredient_list", "compound"),
    "packaging": ("package", "package_type", "pack"),
    "fat": ("fats", "fat_content"),
    "sugar": ("sugars", "sugar_content", "sugarContent"),
    "sugar_class": ("sugarType", "sugar_type", "sweetness"),
    "color": ("colour", "product_color", "productColor"),
    "variant": ("variant_name", "variantName", "sku_variant", "skuVariant", "flavor", "taste"),
    "package_size": ("pack_size", "packSize", "net_weight", "netWeight", "net_content", "netContent"),
    "protein": ("proteins",),
    "carbohydrate": ("carbs", "carbohydrates"),
    "calories": ("energy", "kcal"),
    "shelf_life": ("expiration", "expirationDate", "best_before", "bestBefore"),
    "storage_conditions": ("storage", "storageCondition", "storage_conditions_text"),
}

ATTRIBUTE_FIELD_ALIASES = {
    "бренд": "brand",
    "поставщик": "supplier",
    "производитель": "producer",
    "изготовитель": "manufacturer",
    "страна": "country",
    "страна производства": "country",
    "страна происхождения": "country",
    "состав": "composition",
    "упаковка": "packaging",
    "жирность": "fat_percent",
    "сахар": "sugar",
    "тип сахара": "sugar_class",
    "содержание сахара": "sugar",
    "цвет": "color",
    "вариант": "variant",
    "вкус": "variant",
    "размер упаковки": "package_size",
    "масса нетто": "package_size",
    "объем": "volume",
    "объём": "volume",
    "белки": "protein",
    "белок": "protein",
    "углеводы": "carbohydrate",
    "калории": "calories",
    "калорийность": "calories",
    "срок годности": "shelf_life",
    "условия хранения": "storage_conditions",
}

ATTRIBUTE_CONTAINER_KEYS = (
    "attributes",
    "characteristics",
    "properties",
    "parameters",
    "features",
    "specs",
    "product_properties",
    "productProperties",
)

PRODUCT_STATE_KEYWORDS = (
    ("слабосолен", "Слабосолёный"),
    ("слабосолён", "Слабосолёный"),
    ("заморож", "Замороженный"),
    ("охлажд", "Охлаждённый"),
    ("копчен", "Копчёный"),
    ("копчён", "Копчёный"),
    ("маринован", "Маринованный"),
    ("вялен", "Вяленый"),
    ("сушен", "Сушёный"),
    ("сушён", "Сушёный"),
    ("солен", "Солёный"),
    ("солён", "Солёный"),
)

PRODUCT_FORM_KEYWORDS = (
    ("филе", "Филе"),
    ("стейк", "Стейк"),
    ("фарш", "Фарш"),
    ("кусоч", "Кусочки"),
    ("нарезк", "Нарезка"),
    ("тушк", "Тушка"),
    ("котлет", "Котлеты"),
    ("палочк", "Палочки"),
    ("порцион", "Порционный"),
    ("потрош", "Потрошёный"),
    ("голов", "С головой"),
)
