"""Convert an explicit local ParserRIba artifact to Markdown for audit work."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_DIR = ROOT_DIR / "data" / "converted_markdown"

TEXT_SUFFIXES = {".md", ".txt", ".log"}
DENIED_DIRS = {
    ".git",
    ".venv",
    ".build-venv",
    ".pytest_cache",
    ".playwright-mcp",
    ".yepcode",
    "__pycache__",
    "build",
    "dist",
    "profiles",
}
DENIED_SUFFIXES = {".db", ".sqlite", ".sqlite3", ".mmdb", ".pyc"}
DENIED_FILENAMES = {".env"}
SENSITIVE_NAME_RE = re.compile(
    r"(cookie|cookies|token|secret|credential|auth|proxy|captcha)",
    re.IGNORECASE,
)


class ConversionSafetyError(ValueError):
    """Raised when a requested file is outside the safe conversion boundary."""


def _is_relative_to(path: Path, parent: Path) -> bool:
    try:
        path.relative_to(parent)
    except ValueError:
        return False
    return True


def resolve_workspace_path(raw_path: str) -> Path:
    path = Path(raw_path)
    if not path.is_absolute():
        path = ROOT_DIR / path
    resolved = path.resolve()
    if not _is_relative_to(resolved, ROOT_DIR):
        raise ConversionSafetyError("Source file must be inside the ParserRIba workspace.")
    if not resolved.exists() or not resolved.is_file():
        raise ConversionSafetyError("Source path must point to an existing file.")
    return resolved


def validate_source_path(path: Path) -> None:
    relative_parts = set(path.relative_to(ROOT_DIR).parts[:-1])
    if relative_parts.intersection(DENIED_DIRS):
        raise ConversionSafetyError("Source file is in a local/runtime-only denied directory.")
    if path.name in DENIED_FILENAMES:
        raise ConversionSafetyError("Source file name is denied for conversion.")
    if path.suffix.lower() in DENIED_SUFFIXES:
        raise ConversionSafetyError("Source file type is denied for conversion.")
    if SENSITIVE_NAME_RE.search(path.name):
        raise ConversionSafetyError("Source file name looks sensitive; refuse automatic conversion.")


def resolve_output_path(source: Path, raw_output: str | None) -> Path:
    if raw_output:
        output = Path(raw_output)
        if not output.is_absolute():
            output = ROOT_DIR / output
        resolved = output.resolve()
        if not _is_relative_to(resolved, ROOT_DIR):
            raise ConversionSafetyError("Output path must stay inside the ParserRIba workspace.")
        return resolved

    relative = source.relative_to(ROOT_DIR)
    safe_stem = "__".join(relative.with_suffix("").parts)
    return DEFAULT_OUTPUT_DIR / f"{safe_stem}.md"


def _read_text_file(path: Path) -> str:
    for encoding in ("utf-8-sig", "utf-8", "cp1251"):
        try:
            return path.read_text(encoding=encoding)
        except UnicodeDecodeError:
            continue
    return path.read_text(encoding="utf-8", errors="replace")


def convert_to_markdown(source: Path) -> str:
    if source.suffix.lower() in TEXT_SUFFIXES:
        return _read_text_file(source)

    from markitdown import MarkItDown

    result = MarkItDown(enable_plugins=False).convert(source)
    return str(result.text_content)


def build_header(source: Path) -> str:
    relative = source.relative_to(ROOT_DIR).as_posix()
    return (
        f"# Converted Artifact: `{relative}`\n\n"
        "Generated by `scripts/convert_artifact_to_markdown.py` for local "
        "ParserRIba audit/context work. Review before sharing outside the "
        "workspace.\n\n"
        "---\n\n"
    )


def write_markdown(source: Path, output: Path, *, force: bool) -> None:
    if output.exists() and not force:
        raise ConversionSafetyError("Output file already exists. Use --force to overwrite it.")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_header(source) + convert_to_markdown(source), encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert one safe local ParserRIba artifact to Markdown."
    )
    parser.add_argument("source", help="File inside the ParserRIba workspace.")
    parser.add_argument(
        "--output",
        help="Markdown output path inside the workspace. Defaults to data/converted_markdown/.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing output file.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        source = resolve_workspace_path(args.source)
        validate_source_path(source)
        output = resolve_output_path(source, args.output)
        write_markdown(source, output, force=bool(args.force))
    except ConversionSafetyError as exc:
        sys.stderr.write(f"Conversion refused: {exc}\n")
        return 2
    except Exception as exc:  # pragma: no cover - keeps CLI failure readable.
        sys.stderr.write(f"Conversion failed: {exc}\n")
        return 1

    sys.stdout.write(f"Markdown written: {output}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
